;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-buffer
        beginning-of-visual-line
        c-electric-delete-forward
        clipboard-kill-ring-save
        comint-delchar-or-maybe-eof
        cua-copy-region
        cua-paste
        delete-indentation
        duplicate-line
        electric-newline-and-maybe-indent
        end-of-visual-line
        hydra-string-inflection/nil
        hydra-string-inflection/string-inflection-camelcase-and-exit
        hydra-string-inflection/string-inflection-lower-camelcase-and-exit
        hydra-string-inflection/string-inflection-underscore-and-exit
        hydra-string-inflection/string-inflection-upcase-and-exit
        indent-for-tab-command
        insert-register
        kill-visual-line
        kill-whole-visual-line
        left-of-visual-line
        mark-sexp
        markdown-cycle
        markdown-demote
        markdown-exdent-or-delete
        markdown-outdent-or-delete
        markdown-promote
        move-line-region-up
        ns-copy-including-secondary
        org-delete-char
        org-fill-paragraph
        org-self-insert-command
        py-electric-colon
        right-of-visual-line
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yank-rectangle
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-mode
        ace-window
        eval-print-last-sexp
        helm-find-files
        hydra--negative-argument
        hydra-file-shortcuts/body
        hydra-multiple-cursors/body
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/skip-to-next-like-this
        hydra-multiple-cursors/mc/skip-to-previous-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        hydra-multiple-cursors/nil
        hydra-string-inflection/body
        ignore
        save-buffer
        ))
